export const CONTACT_REQUEST = "CONTACT_REQUEST";
export const CONTACT_SUCCESS = "CONTACT_SUCCESS";
export const CONTACT_FAIL = "CONTACT_FAIL";
export const CONTACT_RESET = "CONTACT_RESET";

export const CONTACT_DETAILS_REQUEST = "CONTACT_DETAILS_REQUEST";
export const CONTACT_DETAILS_SUCCESS = "CONTACT_DETAILS_SUCCESS";
export const CONTACT_DETAILS_FAIL = "CONTACT_DETAILS_FAIL";
export const CONTACT_DETAILS_RESET = "CONTACT_DETAILS_RESET";

// export const CONTACT_DETAILT_BY_ID_REQUEST = "CONTACT_DETAILT_BY_ID_REQUEST";
// export const CONTACT_DETAILT_BY_ID_SUCCESS = "CONTACT_DETAILT_BY_ID_SUCCESS";
// export const CONTACT_DETAILT_BY_ID_FAIL = "CONTACT_DETAILT_BY_ID_FAIL";
// export const CONTACT_DETAILT_BY_ID_RESET = "CONTACT_DETAILT_BY_ID_RESET";

export const CONTACT_DELETE_REQUEST = "CONTACT_DELETE_REQUEST";
export const CONTACT_DELETE_SUCCESS = "CONTACT_DELETE_SUCCESS";
export const CONTACT_DELETE_FAIL = "CONTACT_DELETE_FAIL";
