export const USER_GOOGLE_LOGIN_REQUEST = "USER_GOOGLE_LOGIN_REQUEST";
export const USER_GOOGLE_LOGIN_SUCCESS = "USER_GOOGLE_LOGIN_SUCCESS";
export const USER_GOOGLE_LOGIN_FAIL = "USER_GOOGLE_LOGIN_FAIL";
export const USER_GOOGLE_LOGOUT = "USER_GOOGLE_LOGOUT";
